### ISSUE TITLE
generation of full-reports

### ISSUE THREAD

**Issue by macd2** [ysdede/lazarus3#1]
Hello,
where can i see the code please that generated the content of full-reports?

**Comment by ysdede** [comment]
Hi, please check this:
https://github.com/ysdede/lazarus3/blob/indexedparameters/strategies/lazarus3/__init__.py

**Comment by macd2** [comment]
thanks i had a look at it, but im still not sure where the actual html report is generated

**Comment by ysdede** [comment]
Jesse framework feeds the raw data to quanstats after backtest to create full reports.  Adding --full-reports paramater to backtesting command makes the trick.

**Comment by macd2** [comment]
awesome thanks !
